@baseurl= {{$dotenv OKAPI_URL}}
@tenant={{$dotenv OKAPI_TENANT}}
@username={{$dotenv FOLIO_USER}}
@password={{$dotenv FOLIO_PASSWORD}}
@permLoanId={{$dotenv PERMANENTLOANTYPEID}}
@token={{login.response.headers.x-okapi-token}}

###

# Template
GET {{baseurl}}/
Content-Type: application/json
Accept: application/json
x-okapi-tenant: {{tenant}}
x-okapi-token: {{token}}


###

# Login
// @name login
POST {{baseurl}}/authn/login
Content-Type: application/json
Accept: application/json
x-okapi-tenant: {{tenant}}

{
  "username":"{{username}}",
  "password":"{{password}}"
}

###

# Get requests
GET {{baseurl}}/circulation/requests?query=(requestType=="Recall" and status="Open - Not yet filled")&limit=500
Content-Type: application/json
Accept: application/json
x-okapi-tenant: {{tenant}}
x-okapi-token: {{token}}

###

# GET Available
GET {{baseurl}}/inventory/items?query=(instance.id=="d8043acd-b35f-49f3-89f8-fd7051277eac" AND status.name=="Available" AND permanentLoanTypeId=="{{permLoanId}}")&limit=100
Content-Type: application/json
Accept: application/json
x-okapi-tenant: {{tenant}}
x-okapi-token: {{token}}

###

# GET Available
GET {{baseurl}}/inventory/items?query=(instance.id=="0b20989d-8534-49e0-88b0-b4f96462ff94" AND status.name=="Available")&limit=100
Content-Type: application/json
Accept: application/json
x-okapi-tenant: {{tenant}}
x-okapi-token: {{token}}

###

# Move request to new item
POST {{baseurl}}/circulation/requests/56198e73-d617-4183-8bcf-3526a2dfbcec/move
Content-Type: application/json
Accept: application/json
x-okapi-tenant: {{tenant}}
x-okapi-token: {{token}}

{
  "destinationItemId":"dcda70ec-227e-4994-a3b3-80b6a00fc608",
  "requestType": "Page"
}

###